//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleEndpointClient.MultipleEndpointClientWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MultipleEndpointClientWCF.IGoodStockService")]
    public interface IGoodStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGoodStockService/GetStockPrice", ReplyAction="http://tempuri.org/IGoodStockService/GetStockPriceResponse")]
        double GetStockPrice(string ticker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGoodStockService/GetStockPrice", ReplyAction="http://tempuri.org/IGoodStockService/GetStockPriceResponse")]
        System.Threading.Tasks.Task<double> GetStockPriceAsync(string ticker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGoodStockServiceChannel : MultipleEndpointClient.MultipleEndpointClientWCF.IGoodStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoodStockServiceClient : System.ServiceModel.ClientBase<MultipleEndpointClient.MultipleEndpointClientWCF.IGoodStockService>, MultipleEndpointClient.MultipleEndpointClientWCF.IGoodStockService {
        
        public GoodStockServiceClient() {
        }
        
        public GoodStockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoodStockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoodStockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoodStockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetStockPrice(string ticker) {
            return base.Channel.GetStockPrice(ticker);
        }
        
        public System.Threading.Tasks.Task<double> GetStockPriceAsync(string ticker) {
            return base.Channel.GetStockPriceAsync(ticker);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MultipleEndpointClientWCF.IGreatStockService")]
    public interface IGreatStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreatStockService/GetStockPriceFast", ReplyAction="http://tempuri.org/IGreatStockService/GetStockPriceFastResponse")]
        double GetStockPriceFast(string ticker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreatStockService/GetStockPriceFast", ReplyAction="http://tempuri.org/IGreatStockService/GetStockPriceFastResponse")]
        System.Threading.Tasks.Task<double> GetStockPriceFastAsync(string ticker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreatStockServiceChannel : MultipleEndpointClient.MultipleEndpointClientWCF.IGreatStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreatStockServiceClient : System.ServiceModel.ClientBase<MultipleEndpointClient.MultipleEndpointClientWCF.IGreatStockService>, MultipleEndpointClient.MultipleEndpointClientWCF.IGreatStockService {
        
        public GreatStockServiceClient() {
        }
        
        public GreatStockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreatStockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreatStockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreatStockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetStockPriceFast(string ticker) {
            return base.Channel.GetStockPriceFast(ticker);
        }
        
        public System.Threading.Tasks.Task<double> GetStockPriceFastAsync(string ticker) {
            return base.Channel.GetStockPriceFastAsync(ticker);
        }
    }
}
